### ISSUE TITLE
Metadata sharing

### ISSUE THREAD

**Issue by collinepoirier** [PRIME-RE/prime-re.github.io#54]
## Resource info table    

|                     |                                                                                         |
| :------------------ | :-------------------------------------------------------------------------------------- |
| **Name**            |  Metadata sharing                                           |    
| **Authors**         |  Colline Poirier and Andrew Fox                                                     |
| **Description**     | This resource describes recommendations to share metadata to enrich NHP neuroimaging data (what, where and how).                              |
| **Documentation**   | In progress |
| **Link**            |  |
| **Language**        |                |
| **Publication**     | |
| **Communication**   |  email                                       |
| **Restrictions**    |                               |
| **Category**        |                              |
  
** Please check the applicable boxes**    
- [ x] All required ethical approval (human/animal) for the development of this resource was obtained  
- [x ] No ethical approval (human/animal) was required for the development of this resource      
- [ ] Do NOT include this resource in periodic mailings about new resources on PRIME-RE

**Comment by pcklink** [comment]
Hi Colline, I'm not quite sure what to do with this at the moment. It is posted as a new resource, but doesn't have any content or a link to content. I suspect this is a paper-to-be-(coming out)? If I'd put this online now it doesn't really help users in finding these recommendations, so perhaps we can wait until there is content to refer to?

**Comment by collinepoirier** [comment]
Hi Chris,
Chris Petkov has asked me to create such a page now, in order to put the link in the corresponding publication that will be published in the NeuroImage special issue. The paper is accepted and I have received the uncorrected proof. I think that the idea was to include the link to PRIME-RE webpage in the corrected version of the proof, then to receive the article doi from NeuroImage shortly after, and then to update the description of the resource with the paper reference. Would it be suitable?.
Best wishes,
Colline

Colline Poirier, PhD
Newcastle University Research Fellow
Biosciences Institute
Medical School
Framlington Place
NE1 7RU Newcastle-upon-Tyne

Telephone number: 0191 208 8210

**Comment by pcklink** [comment]
Ah, I see. I think I talked about this with Chris P. What we could is create a page similar to what I did for the 'Head-cap' paper ([here](https://prime-re.github.io/hardware_and_protocols/protective_headcap.html)) but whether this is suitable and where it should be located (url-wise) will somewhat depend on content. My best guess would be that it would be suitable to list it under the 'Protocols & Experimental Design' header on the [Hardware & Protocols page](https://prime-re.github.io/hardware) as 'Metadata sharing' and have that link to a dedicated page [here](https://prime-re.github.io/hardware_and_protocols/metadata_sharing.html), which is now still empty. You can link to that page in the paper if you want, although it would be safer to refer to the root [https://prime-re.github.io](https://prime-re.github.io) since these 'protocol resources' are only starting to get established and a reorganization may at some point be necessary. Will that work?

**Comment by collinepoirier** [comment]
Hi,
Yes, that would work. I will reference the PRIME-RE root webpage in the manuscript.
Could you please let me know how I can update the metadata sharing page in the future?
Thanks.
Best wishes,
Colline

Colline Poirier, PhD
Newcastle University Research Fellow
Biosciences Institute
Medical School
Framlington Place
NE1 7RU Newcastle-upon-Tyne

Telephone number: 0191 208 8210

**Comment by pcklink** [comment]
The easiest way to update is probably to provide content in this (or a new) issue and one of the PRIME-RE team members can transfer it to the page (which currently exist but is not linked anywhere on the website.

Alternatively you can directly edit the page on GitHub using a pull request, but this seems a little bit more involved.

**Comment by pcklink** [comment]
Done
